### ISSUE TITLE
unable to create new (or save) ldap host configuration in Shmanic LDAP: Hosts

### ISSUE THREAD

**Issue by billtzim** [jbrailas/JMapMyLDAP_v5#3]
When trying to create a new ldap host configuration, although all the fields are filled properly i am unable to save. The form says that i didn't give name, host, port.

Additionaly, the default values that show in the form look that might be (forgotten?) real values.

I also tried to populate the fileds directly in the database by copy-pasting the values from a working Joomla 3.10 installation. The values show on form load but when saving the form the defaults show up and the error messages that i didn't give name, host, port.

System 
PHP 8.2 (latest)
mysql 8.0
Joomla 5.0.3

**Comment by jbrailas** [comment]
Thank you for your comments, I will fix the issues but not until the end of the month.

**Comment by billtzim** [comment]
After the latest code commits the problem still exists

**Comment by jbrailas** [comment]
This issue has been resolved now.
