### ISSUE TITLE
Missing or wrong file in pkg_ldap_sso_core.xml of the installation file pkg_ldap_sso_core_v5.zip  

### ISSUE THREAD

**Issue by billtzim** [jbrailas/JMapMyLDAP_v5#5]
in the pkg_ldap_sso_core.xml of the package the below line exists that breaks the installation due to the file not existing.

`<file type="file" id="cli_shmanic_ldap">cli_shmanic_ldap.zip</file>`

**Comment by jbrailas** [comment]
It has been updated, thanks!
